apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shirahoshiii/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000